# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  workflow_dispatch:
  schedule: 
      - cron: '0,30 * * * *'


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout Repository

      - name: Run  Script and push changes
        run: chmod +x run.sh && ./run.sh   && df -h && pwd && df -h .
      - name: build
        run: chmod +x static-run.sh && ./static-run.sh     
        env: 
          INGEST_PATH: ${{ secrets.INGEST_PATH }}
